site_name: README STITCH
plugins:
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: false
      nav_repos:
        - name: product
          import_url: https://github.com/pbj-writes/readme_mkdocs
          imports: [/docs/index.md]
        - name: repo-1
          import_url: https://github.com/pbj-writes/repo_1
          # forward slash is needed in '/README.md' so that only the README.md in the root
          # directory is imported and not all README.md files.
          imports: [docs/install.md, docs/inventory.md, /README.md]
          branch: main
nav:
  - Product:
      - Home: readme_mkdocs/docs/index.md
      - Repo 1: repo-1/README.md
     # - Inventory: repo-1/docs/inventory.md
      #- Install: repo-1/docs/install.md
  # you can still use the !import statement
    - MkdocStrings: '!import https://github.com/mkdocstrings/mkdocstrings'