site_name: README STITCH
nav:
  - Home: index.md
  - Repo 1: 'Repo 1'

plugins:
  - search
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: true
      # if set the docs directory will not be removed when importing docs. When using this with a nav section in an imported repo
      # you must keep the docs directory in the path (e.g., docs/path/to/file.md).
      keep_docs_dir: true
      repos:
          # There will be a navigation section with this section name
        - section: Repo 1
          # you can define the edit uri path
          import_url: 'https://github.com/pbj-writes/repo_1?edit_uri=/blob/master/'

plugins:
  - search
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: false
      nav_repos:
        - name: Product
          import_url: https://github.com/pbj-writes/readme_mkdocs
          imports: [/docs/index.md]
        - name: Repo 1
          import_url: https://github.com/pbj-writes/repo_1
          # forward slash is needed in '/README.md' so that only the README.md in the root
          # directory is imported and not all README.md files.
          imports: [
            docs/install.md, docs/inventory.md, /README.md
            ]

nav:
  - 
  - Backstage:
      - Home: backstage/README.md
      - Integration: backstage/docs/integrations/index.md
      - Publishing: backstage/docs/publishing.md
  - FastAPI: fast-api/docs/en/docs/index.md
  # you can still use the !import statement
  - MkdocStrings: '!import https://github.com/mkdocstrings/mkdocstrings'